language: php

before_install:
  - curl -s http://getcomposer.org/installer | php -- --install-dir=./bin
  - php ./bin/composer.phar install --dev

php:
  - 5.3
  - 5.4

notifications:
  email:
    - travis@bastian-feder.de
